/*
 *  Copyright (C) 2003-2016 Altair Engineering, Inc. All rights reserved.
 *
 *  ALTAIR ENGINEERING INC. Proprietary and Confidential. Contains Trade Secret
 *  Information. Not for use or disclosure outside ALTAIR and its licensed
 *  clients. Information contained herein shall not be decompiled, disassembled,
 *  duplicated or disclosed in whole or in part for any purpose. Usage of the
 *  software is only as explicitly permitted in the end user software license
 *  agreement.
 *
 *  Copyright notice does not imply publication.
 *
 */
#include <pbs_config.h>   /* the master config generated by configure */

#include <stdio.h>
#include <stdlib.h>
#include "pbs_rescspec.h"
#include "parser.h"
#include "tok.h"

/* static prototypes */
static void print_rescspec_tree_rec(rescspec *root, FILE *fp, int level);

extern char *yytext;
extern rescspec *rescspec_root;

/*
 *
 *	make_tree - make a subnode of a larger rescspec parse tree
 *		    used by the bison generated parser
 *
 *	returns the root of the subtree
 *
 */
rescspec *
make_tree(rescspec *root, rescspec *left, rescspec *right)
{
	if (left != NULL) {
		root->left_child = left;
		left->parent = root;
	}

	if (right != NULL) {
		root->right_child = right;
		right->parent = root;
	}

	return root;
}

/*
 *
 *	tree_finished - called form the parser when it is done parsing
 *			we save a pointer to the tree so it can be returned
 *			from parse_rescspec()
 *
 *	returns the root
 *
 */
rescspec *
tree_finished(rescspec *root)
{
	rescspec_root = root;

	return root;
}

/*
 *
 *	print_rescspec_tree - print out a rescspec parsetree to a file
 *
 * 	returns nothing
 */
void
print_rescspec_tree(rescspec *root, FILE *fp)
{

	if (fp == NULL)
		fp = stdout;

	print_rescspec_tree_rec(root, fp, 0);
}

/*
 *
 *	print_rescspec_tree_rec - recursive helper function to print a tree
 *
 *	  root  - the root of the spec tree
 *	  fp    - the file to print to (could be stdout)
 *	  level - the current tree level
 *
 *	returns nothing
 *
 */
static void
print_rescspec_tree_rec(rescspec *root, FILE *fp, int level)
{
	if (root == NULL)
		return;

	fprintf(fp, "%*s%s %s\n", level * 3, " ", root->lex_info, trans_sym_name(root->token_code));

	print_rescspec_tree_rec(root->left_child, fp, level + 1);
	print_rescspec_tree_rec(root->right_child, fp, level + 1);
}
